POST http://localhost:3003/product/create
Content-Type: application/json

{
    "name": "",
    "tags": ["algodão", "verão", "camisa" ]
}
###

GET http://localhost:3003/product?name=
Content-Type: application/json

{
    "tags": ["bolsa"]
}