POST http://localhost:3003/payment/register
Content-Type: application/json

{
    "client_id": "id1",
    "buyer_name": "Eric Felipe",
    "buyer_email": "eric@dev.com",
    "buyer_cpf": "456.092.074-49",
    "payment_amount": 400,
    "payment_type": "CREDITCARD",
    "card_holder_name": "Eric Felipe",
    "card_number": "6786782398328703",
    "card_expiration_date": "12/2030",
    "card_cvv": "938"
}
###
GET  http://localhost:3003/payment/status?id=102ed0d0-5337-4994-bcea-93551f372811&payment_type=CREDITCARD
Content-Type: application/json