POST http://localhost:3003/payment/slip
Content-Type: application/json

{
    "client_id":"id1",
    "buyer_name":"Eric Felipe",
    "buyer_email":"eric@dev.com",
    "buyer_cpf":"98765424502",
    "payment_amount":500,
    "payment_type":"SLIP"
}

###

POST http://localhost:3003/payment/creditCard
Content-Type: application/json

{
    "client_id": "id1",
    "buyer_name": "Eric Felipe",
    "buyer_email": "eric@dev.com",
    "buyer_cpf": "76325662305",
    "payment_amount": 800,
    "payment_type": "CREDITCARD",
    "card_holder_name": "ERIC F SILVA",
    "card_number": "7642387698236498",
    "card_expiration_date": "09/24",
    "card_cvv": "379"
}
###
GET  http://localhost:3003/payment/byCreditCard/09661108-a6a8-49d3-87e7-b2e0fb2dda4d
Content-Type: application/json
###
GET  http://localhost:3003/payment/bySlip/9c86f13a-7829-429d-a51b-ba4d851b8ba6
Content-Type: application/json