POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Eduardo",
    "email":"jegue@gmail.com",
    "password":"jegue123"
}

###

GET http://localhost:3003/users
Content-Type: application/json
